#ifndef POOL_CONTAINER_TEST_H
#define POOL_CONTAINER_TEST_H

#ifndef POOL_CONTAINER_TEST_DISABLE
    //#define POOL_CONTAINER_TEST_DISABLE 1
#endif /* POOL_CONTAINER_TEST_DISABLE */


#ifndef POOL_CONTAINER_TEST_DISABLE

int poolContainerTest(int randomSeed, int testCnt);

#endif /* POOL_CONTAINER_TEST_DISABLE */



#endif /* POOL_CONTAINER_TEST_H */
